# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dylan Hawley
email: dylanthomashawley@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   A collection of posts, projects, and photographs by one based man.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dhawley.com" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: dylanhawley/mono-lite
# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

permalink: /:title/

mono-lite:
  intro_description: >-
    I'm an AI Engineer / Creative Technologist / Space Enthusiast, currently building computer vision tools at Booz Allen in Washington, DC. My work often explores ways to make machine learning more intuitive, useful, or just plain cooler.

  secondary_description: >-
    Outside of work, I'm usually either out cycling, climbing, or planning my next backcountry adventure with my fiancée—or inside coding or playing poker. I love building things that blend technical rigor with a sense of play, whether that's for space, the outdoors, or anything in between.
  
  social_links:
    github: dylanhawley
    linkedin: dylanhawley
    opengraph: assets/dh-open-graph.png
    twitter: dylanthawley
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
